{{- if or .Values.envConfig .Values.fileConfig.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cron-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cron-chart.labels" . | nindent 4 }}
data:
  {{- if .Values.envConfig -}}
  {{- toYaml .Values.envConfig | nindent 2 }}
  {{- end }}
  {{- if .Values.fileConfig.create -}}
  {{- toYaml .Values.fileConfig.files | nindent 2 }}
  {{- end }}
{{- end }}

---


